# encoding: utf-8

# === Usage === #
# Run gem bundle for installation. You have to have bundler gem installed.

# http://github.com/wycats/bundler
# http://litanyagainstfear.com/blog/2009/10/14/gem-bundler-is-the-future
# http://yehudakatz.com/2009/11/03/using-the-new-gem-bundler-today
# http://www.engineyard.com/blog/2009/using-the-rubygems-bundler-for-your-app

# === Shared Gems === #
# Specify a dependency on rango. When the bundler downloads gems,
# it will download rango as well as all of rango' dependencies

# rango stack
gem "rango"#, git: "git://github.com/botanicus/rango.git"
gem "rack"#, git: "git://github.com/rack/rack.git"
gem "tilt"#, git: "git://github.com/rtomayko/tilt.git"

# router
gem "usher"#, git: "git://github.com/joshbuddy/usher.git"

# template engine
gem "haml"#, git: "git://github.com/nex3/haml.git"

# NOTE: do not use require_as: nil because if you do so, bundler will require the library anyway
# Check last section of http://wiki.github.com/merb/merb/howto-using-the-bundler for more informations
only(:bundle) do
  gem "thin"#, git: "git://github.com/macournoyer/thin.git" # there seems to be some problems with latest thin
  #gem "unicorn"#, git: "git://repo.or.cz/unicorn.git"
  gem "racksh"#, git: "git://github.com/sickill/racksh.git"
  gem "shotgun"#, git: "git://github.com/rtomayko/shotgun.git"
end

gem "simple-logger"#, git: "git://github.com/botanicus/simple-logger.git"
gem "media-path"#, git: "git://github.com/botanicus/media-path.git"

# === Environment-Specific Setup === #
only(:test) do
  gem "rspec"#, git: "git://github.com/dchelimsky/rspec.git"
  gem "rack-test", require_as: "rack/test"#, git: "git://github.com/brynary/rack-test.git"
end

# === Bundler Setup === #
# Specify where the bundled gems should be stashed. This directory will
# be a gem repository where all gems are downloaded to and installed to.
#
# This is an optional setting.
# The default is: vendor/gems
bundle_path "gems"

# Specify where gem executables should be copied to.
#
# This is an optional setting.
# The default is: bin
bin_path "bin"
