# encoding: utf-8

# === Usage === #
# Run gem bundle for installation. You have to have bundler gem installed.

# http://github.com/wycats/bundler
# http://litanyagainstfear.com/blog/2009/10/14/gem-bundler-is-the-future
# http://yehudakatz.com/2009/11/03/using-the-new-gem-bundler-today
# http://www.engineyard.com/blog/2009/using-the-rubygems-bundler-for-your-app

gem "rails"                    # git: "git://github.com/rails/rails.git"
gem "media-path"               # git: "git://github.com/botanicus/media-path.git"
gem "rspec", only: :test       # git: "git://github.com/dchelimsky/rspec.git"
gem "rspec-rails", only: :test # git: "git://github.com/dchelimsky/rspec-rails.git"

# === Bundler Setup === #
# Specify where the bundled gems should be stashed. This directory will
# be a gem repository where all gems are downloaded to and installed to.
#
# This is an optional setting.
# The default is: vendor/gems
bundle_path "gems"

# Specify where gem executables should be copied to.
#
# This is an optional setting.
# The default is: bin
bin_path "bin"
